apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-app
  namespace: avengers
  labels:
    build_number: ${BUILD_NUMBER}
    app: monitoring-app
    role: rolling-update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoring-app
        image: mahi4847/monitoring-app:latest
        ports:
        - containerPort: 80
    strategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-app-c
  namespace: avengers
  labels:
    app: monitoring-app
spec:
  type: NodePort
  ports:
    port: 8080
    targetPort: 8080
    nodePort: 30100
  selector:
    app: monitoring-app
